### ISSUE TITLE
BMR - NEAR Module

### ISSUE THREAD

**Issue by MuhammedIrfan** [icon-project/icon-bridge#48]
## Features

- [ ] icon-project/icon-bridge-planning#49
- [ ] icon-project/icon-bridge-planning#48
- [x] icon-project/icon-bridge#111
- [ ] icon-project/icon-bridge-planning#47
