### ISSUE TITLE
Merge Native Coin BSH to BTS - NEAR

### ISSUE THREAD

**Issue by MuhammedIrfan** [icon-project/icon-bridge#50]
## Features

- [x] icon-project/icon-bridge#152
- [x] icon-project/icon-bridge#153 
- [x] icon-project/icon-bridge-planning#44
- [ ] icon-project/icon-bridge-planning#43
